// AUTO-GENERATED by .genimg/gen_gallery.py — edit alts there, then re-run.
// AI renders (Gemini, prompts v11). Data-only file per the content/layout rule.
export type GalleryImage = { src: string; alt: string };

export const plantGallery: Record<string, GalleryImage[]> = {
  "capital": [
    { src: "/assets/img/gen/founder-capital.jpg", alt: "YUGA founder Prince Shah in a capital advisory session" },
    { src: "/assets/img/gen/b14_2.jpg", alt: "Fundraising & capital advisory - core process machinery" },
    { src: "/assets/img/gen/b14_3.jpg", alt: "Fundraising & capital advisory - process detail with engineer" },
    { src: "/assets/img/gen/b14_5.jpg", alt: "Fundraising & capital advisory - plant inauguration ceremony" },
  ],
  "company": [
    { src: "/assets/img/gen/founder-company.jpg", alt: "YUGA founder Prince Shah at a commissioned YUGA plant" },
    { src: "/assets/img/gen/b1_3.jpg", alt: "YUGA company overview - process detail with engineer" },
    { src: "/assets/img/gen/a1-q1.jpg", alt: "YUGA company overview - front view" },
    { src: "/assets/img/gen/a1-q2.jpg", alt: "YUGA company overview - left-side view" },
    { src: "/assets/img/gen/a1-q3.jpg", alt: "YUGA company overview - right-side view" },
    { src: "/assets/img/gen/a1-q4.jpg", alt: "YUGA company overview - interior view" },
  ],
  "complete": [
    { src: "/assets/img/gen/founder-industrial.jpg", alt: "YUGA founder Prince Shah leading an industrial plant site visit" },
    { src: "/assets/img/gen/b12_3.jpg", alt: "Complete plant setup - process detail with engineer" },
    { src: "/assets/img/gen/b12_4.jpg", alt: "Complete plant setup - hero product moment" },
    { src: "/assets/img/gen/b12_5.jpg", alt: "Complete plant setup - plant inauguration ceremony" },
    { src: "/assets/img/gen/a12-q1.jpg", alt: "Complete plant setup - front view" },
    { src: "/assets/img/gen/a12-q2.jpg", alt: "Complete plant setup - left-side view" },
    { src: "/assets/img/gen/a12-q3.jpg", alt: "Complete plant setup - right-side view" },
    { src: "/assets/img/gen/a12-q4.jpg", alt: "Complete plant setup - interior view" },
  ],
  "journey": [
    { src: "/assets/img/gen/founder-bio-overview.jpg", alt: "YUGA founder Prince Shah on a plant consulting walkthrough" },
    { src: "/assets/img/gen/b2_2.jpg", alt: "Client journey - idea to income - core process machinery" },
    { src: "/assets/img/gen/b2_3.jpg", alt: "Client journey - idea to income - process detail with engineer" },
    { src: "/assets/img/gen/b2_5.jpg", alt: "Client journey - idea to income - plant inauguration ceremony" },
  ],
  "software": [
    { src: "/assets/img/gen/founder-software.jpg", alt: "YUGA founder Prince Shah reviewing the AI software stack with the tech team" },
    { src: "/assets/img/gen/b13_3.jpg", alt: "AI software in action - process detail with engineer" },
    { src: "/assets/img/gen/b13_5.jpg", alt: "AI software in action - plant inauguration ceremony" },
  ],
};
