// AUTO-GENERATED by .genimg/gen_imagery.py — per-page UNIQUE image roles.
// Slot-used assets are excluded by the generator; every asset appears once site-wide.
export type WeaveImage = { src: string; alt: string };
export interface ProductImagery {
  strip: WeaveImage[];          // quad views — hover-expand strip
  overviewSide: WeaveImage | null;   // interior quad beside the overview text
  machineSide: WeaveImage | null;    // process-detail scene in the machinery section
  ambient: WeaveImage | null;        // full-width parallax banner
  ceremony: WeaveImage | null;       // inauguration shot beside documents
  blueprint: WeaveImage | null;      // full 4-angle sheet panel
}

export const productImagery: Record<string, ProductImagery> = {
  "bio-bitumen": {
    strip: [{ src: "/assets/img/gen/a3-q2.jpg", alt: "Bio-bitumen plant - left-side view" }, { src: "/assets/img/gen/a3-q3.jpg", alt: "Bio-bitumen plant - right-side view" }],
    overviewSide: { src: "/assets/img/gen/a3-q4.jpg", alt: "Bio-bitumen plant - interior view" },
    machineSide: null,
    ambient: { src: "/assets/img/gen/b3_4.jpg", alt: "Bio-bitumen plant - hero product moment" },
    ceremony: { src: "/assets/img/gen/b3_5.jpg", alt: "Bio-bitumen plant - plant inauguration ceremony" },
    blueprint: { src: "/assets/img/gen/a3-sheet.jpg", alt: "Bio-bitumen plant - one plant from four angles" },
  },
  "plastic-to-fuel": {
    strip: [{ src: "/assets/img/gen/a4-q1.jpg", alt: "Plastic-to-fuel pyrolysis plant - front view" }, { src: "/assets/img/gen/a4-q2.jpg", alt: "Plastic-to-fuel pyrolysis plant - left-side view" }, { src: "/assets/img/gen/a4-q3.jpg", alt: "Plastic-to-fuel pyrolysis plant - right-side view" }],
    overviewSide: { src: "/assets/img/gen/a4-q4.jpg", alt: "Plastic-to-fuel pyrolysis plant - interior view" },
    machineSide: { src: "/assets/img/gen/b4_3.jpg", alt: "Plastic-to-fuel pyrolysis plant - process detail with engineer" },
    ambient: { src: "/assets/img/gen/b4_4.jpg", alt: "Plastic-to-fuel pyrolysis plant - hero product moment" },
    ceremony: { src: "/assets/img/gen/b4_5.jpg", alt: "Plastic-to-fuel pyrolysis plant - plant inauguration ceremony" },
    blueprint: { src: "/assets/img/gen/a4-sheet.jpg", alt: "Plastic-to-fuel pyrolysis plant - one plant from four angles" },
  },
  "rubber-to-fuel": {
    strip: [{ src: "/assets/img/gen/a5-q1.jpg", alt: "Tyre pyrolysis plant - front view" }, { src: "/assets/img/gen/a5-q2.jpg", alt: "Tyre pyrolysis plant - left-side view" }, { src: "/assets/img/gen/a5-q3.jpg", alt: "Tyre pyrolysis plant - right-side view" }, { src: "/assets/img/gen/b5_2.jpg", alt: "Tyre pyrolysis plant - core machinery" }],
    overviewSide: { src: "/assets/img/gen/a5-q4.jpg", alt: "Tyre pyrolysis plant - interior view" },
    machineSide: { src: "/assets/img/gen/b5_3.jpg", alt: "Tyre pyrolysis plant - process detail with engineer" },
    ambient: { src: "/assets/img/gen/b5_4.jpg", alt: "Tyre pyrolysis plant - hero product moment" },
    ceremony: { src: "/assets/img/gen/b5_5.jpg", alt: "Tyre pyrolysis plant - plant inauguration ceremony" },
    blueprint: { src: "/assets/img/gen/a5-sheet.jpg", alt: "Tyre pyrolysis plant - one plant from four angles" },
  },
  "bitumen-emulsion": {
    strip: [{ src: "/assets/img/gen/a6-q1.jpg", alt: "Bitumen emulsion plant - front view" }, { src: "/assets/img/gen/a6-q2.jpg", alt: "Bitumen emulsion plant - left-side view" }, { src: "/assets/img/gen/a6-q3.jpg", alt: "Bitumen emulsion plant - right-side view" }, { src: "/assets/img/gen/b6_4.jpg", alt: "Bitumen emulsion plant - hero product moment" }],
    overviewSide: { src: "/assets/img/gen/a6-q4.jpg", alt: "Bitumen emulsion plant - interior view" },
    machineSide: { src: "/assets/img/gen/b6_3.jpg", alt: "Bitumen emulsion plant - process detail with engineer" },
    ambient: { src: "/assets/img/gen/b6_1.jpg", alt: "Bitumen emulsion plant - establishing wide view" },
    ceremony: { src: "/assets/img/gen/b6_5.jpg", alt: "Bitumen emulsion plant - plant inauguration ceremony" },
    blueprint: { src: "/assets/img/gen/a6-sheet.jpg", alt: "Bitumen emulsion plant - one plant from four angles" },
  },
  "pmb-polymer-modified-bitumen": {
    strip: [{ src: "/assets/img/gen/a7-q1.jpg", alt: "PMB plant - front view" }, { src: "/assets/img/gen/a7-q2.jpg", alt: "PMB plant - left-side view" }, { src: "/assets/img/gen/a7-q3.jpg", alt: "PMB plant - right-side view" }],
    overviewSide: { src: "/assets/img/gen/a7-q4.jpg", alt: "PMB plant - interior view" },
    machineSide: { src: "/assets/img/gen/b7_3.jpg", alt: "PMB plant - process detail with engineer" },
    ambient: { src: "/assets/img/gen/b7_4.jpg", alt: "PMB plant - hero product moment" },
    ceremony: { src: "/assets/img/gen/b7_5.jpg", alt: "PMB plant - plant inauguration ceremony" },
    blueprint: { src: "/assets/img/gen/a7-sheet.jpg", alt: "PMB plant - one plant from four angles" },
  },
  "crmb-crumb-rubber-modified-bitumen": {
    strip: [{ src: "/assets/img/gen/a8-q1.jpg", alt: "CRMB plant - front view" }, { src: "/assets/img/gen/a8-q2.jpg", alt: "CRMB plant - left-side view" }, { src: "/assets/img/gen/a8-q3.jpg", alt: "CRMB plant - right-side view" }, { src: "/assets/img/gen/b8_4.jpg", alt: "CRMB plant - hero product moment" }],
    overviewSide: { src: "/assets/img/gen/a8-q4.jpg", alt: "CRMB plant - interior view" },
    machineSide: { src: "/assets/img/gen/b8_3.jpg", alt: "CRMB plant - process detail with engineer" },
    ambient: { src: "/assets/img/gen/b8_1.jpg", alt: "CRMB plant - establishing wide view" },
    ceremony: { src: "/assets/img/gen/b8_5.jpg", alt: "CRMB plant - plant inauguration ceremony" },
    blueprint: { src: "/assets/img/gen/a8-sheet.jpg", alt: "CRMB plant - one plant from four angles" },
  },
  "bitumen-decanter": {
    strip: [{ src: "/assets/img/gen/a9-q1.jpg", alt: "Bitumen decanter plant - front view" }, { src: "/assets/img/gen/a9-q2.jpg", alt: "Bitumen decanter plant - left-side view" }, { src: "/assets/img/gen/a9-q3.jpg", alt: "Bitumen decanter plant - right-side view" }, { src: "/assets/img/gen/b9_4.jpg", alt: "Bitumen decanter plant - hero product moment" }],
    overviewSide: { src: "/assets/img/gen/a9-q4.jpg", alt: "Bitumen decanter plant - interior view" },
    machineSide: { src: "/assets/img/gen/b9_3.jpg", alt: "Bitumen decanter plant - process detail with engineer" },
    ambient: { src: "/assets/img/gen/b9_1.jpg", alt: "Bitumen decanter plant - establishing wide view" },
    ceremony: { src: "/assets/img/gen/b9_5.jpg", alt: "Bitumen decanter plant - plant inauguration ceremony" },
    blueprint: { src: "/assets/img/gen/a9-sheet.jpg", alt: "Bitumen decanter plant - one plant from four angles" },
  },
  "micro-surfacing-emulsion": {
    strip: [],
    overviewSide: { src: "/assets/img/gen/b10_4.jpg", alt: "Micro-surfacing plant - hero product moment" },
    machineSide: { src: "/assets/img/gen/b10_3.jpg", alt: "Micro-surfacing plant - process detail with engineer" },
    ambient: { src: "/assets/img/gen/b10_1.jpg", alt: "Micro-surfacing plant - establishing wide view" },
    ceremony: { src: "/assets/img/gen/b10_5.jpg", alt: "Micro-surfacing plant - plant inauguration ceremony" },
    blueprint: null,
  },
  "blown-oxidised-bitumen": {
    strip: [{ src: "/assets/img/gen/a11-q1.jpg", alt: "Blown bitumen plant - front view" }, { src: "/assets/img/gen/a11-q2.jpg", alt: "Blown bitumen plant - left-side view" }, { src: "/assets/img/gen/a11-q3.jpg", alt: "Blown bitumen plant - right-side view" }, { src: "/assets/img/gen/b11_4.jpg", alt: "Blown bitumen plant - hero product moment" }],
    overviewSide: { src: "/assets/img/gen/a11-q4.jpg", alt: "Blown bitumen plant - interior view" },
    machineSide: { src: "/assets/img/gen/b11_3.jpg", alt: "Blown bitumen plant - process detail with engineer" },
    ambient: { src: "/assets/img/gen/b11_1.jpg", alt: "Blown bitumen plant - establishing wide view" },
    ceremony: { src: "/assets/img/gen/b11_5.jpg", alt: "Blown bitumen plant - plant inauguration ceremony" },
    blueprint: { src: "/assets/img/gen/a11-sheet.jpg", alt: "Blown bitumen plant - one plant from four angles" },
  },
};
